apiVersion: apps/v1
kind: Deployment
metadata:
  name: result
  labels:
    app: result
spec:
  replicas: 1
  selector:
    matchLabels:
      app: result
  template:
    metadata:
      labels:
        app: result
    spec:
      containers:
      - image: 654654478631.dkr.ecr.ap-south-1.amazonaws.com/result-repo/result:33
        name: result
        ports:
        - containerPort: 80
      imagePullSecrets:
        - name: ecr-image-pull-secret