apiVersion: v1
kind: Service
metadata:
  name: vote
  labels:
    app: vote
spec:
  selector:
    app: vote
  type: NodePort
  ports:
  - name: vote-service
    port: 8080
    targetPort: 80

