apiVersion: apps/v1
kind: Deployment
metadata:
  name: vote
  labels:
    app: vote
spec:
  replicas: 1
  selector: 
    matchLabels:
      app: vote
  template:  
    metadata:
      labels:
        app: vote
    spec:
      containers:
      - image: 654654478631.dkr.ecr.ap-south-1.amazonaws.com/vote-repo:vote-repo:43
        name: vote
        ports: 
        - containerPort: 80  
      imagePullSecrets:
      - name: ecr-image-pull-secret

