  apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: worker
    labels:
      app: worker
  spec:
    replicas: 1
    selector:
      matchLabels:
        app: worker
    template:
      metadata:
        labels:
          app: worker
      spec:
        containers:
        - name: worker
          image: 654654478631.dkr.ecr.ap-south-1.amazonaws.com/worker-repo/worker:8
        imagePullSecrets:
        - name: ecr-image-pull-secret
        