version: 0.2
phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR
      - aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 654654478631.dkr.ecr.ap-south-1.amazonaws.com
      - git config --global user.email "vipulkalebag.1317@gmail.com"
      - git config --global user.name "vipul"
      - export BUILD_NUMBER=${CODEBUILD_BUILD_NUMBER}
      - echo Build starting
      # - git clone https://$GITHUB_TOKEN@github.com/vipulkalebag/Capstone_Project_DIM.git
      - ls -l example-voting-app/kube-spec/
  build:
    commands:
      - cd example-voting-app/vote
      - echo Building the Docker image
      - docker build -t vote-repo:${BUILD_NUMBER} .
      - docker tag vote-repo:${BUILD_NUMBER} 654654478631.dkr.ecr.ap-south-1.amazonaws.com/vote-repo:${BUILD_NUMBER}
      - echo Pushing the Docker image to Amazon ECR
      - docker push 654654478631.dkr.ecr.ap-south-1.amazonaws.com/vote-repo:${BUILD_NUMBER}
      - echo Build is successful
    
  post_build:
    commands:
      - echo Running update.sh script to update Kubernetes manifests
      - cd ../kube-spec/
      - chmod -R 777 ../kube-spec/
      - cd ../update_script/
      - chmod +x ././update-kube-spec.sh
      # - chmod +x example-voting-app/update_script/update-kube-spec.sh
      - ./update-kube-spec.sh vote $BUILD_NUMBER




